name: Docker Image CI and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm/v7
        push: true
        tags: simeonevilardo/simeone-mail-bot:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
  
    steps:
    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y sshpass
  
    - name: Deploy to Raspberry Pi
      env:
        IMAGE_NAME: simeonevilardo/simeone-mail-bot:latest
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        DOMAINS: ${{ secrets.DOMAINS }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      run: |
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
  
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST << EOF
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker pull $IMAGE_NAME
          docker stop simeone-mail-bot || true
          docker rm simeone-mail-bot || true
          docker run -d --name simeone-mail-bot \
            --env TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN \
            --env TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID \
            --env DOMAINS=$DOMAINS \
            --env SMTP_SERVER=$SMTP_SERVER \
            --env SMTP_PORT=$SMTP_PORT \
            --env SMTP_USERNAME=$SMTP_USERNAME \
            --env SMTP_PASSWORD=$SMTP_PASSWORD \
            -p 1025:1025 $IMAGE_NAME
        EOF

