name: Docker Image CI and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: simeonevilardo/simeone-mail-bot:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: manual_approval

    steps:
      - name: Docker compose up
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_KEY }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            docker compose -f /home/${{ secrets.HOST_USERNAME }}/simeone-mail-bot/docker-compose.yml down
            docker compose -f /home/${{ secrets.HOST_USERNAME }}/simeone-mail-bot/docker-compose.yml up -d
      
      
    
